CREATE DATABASE EventPlus;

USE EventPlus;

CREATE TABLE TipoUsuario(
	idTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(244) NOT NULL
);

CREATE TABLE TipoEvento(
	idTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario(
	idUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(264) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL,
	idTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario (idTipoUsuario)
);

CREATE TABLE Instituicao(
	idInstituição UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	NomeFantasia VARCHAR(100) NOT NULL,
	Endereço VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL
);

CREATE TABLE Evento(
	idEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	DataEvento DATETIME NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	idTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento (idTipoEvento),
	idInstituição UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao (idInstituição)
);

CREATE TABLE Presenca(
	idPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Presenca BIT NOT NULL,
	idTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario (idTipoUsuario),
	idTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento (idTipoEvento)
);

CREATE TABLE ComentarioEvento(
	idComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Descricao VARCHAR(200) NOT NULL,
	Exibe BIT NOT NULL,
	DataComentario DATETIME NOT NULL,
	idTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario (idTipoUsuario),
	idTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento (idTipoEvento)
);
