CREATE DATABASE DevSchool

USE DevSchool;

CREATE TABLE Tipo_Usuario(
	id_Tipo_Usuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(244) NOT NULL
);

CREATE TABLE Tipo_Evento(
	id_Tipo_Evento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario(
	id_Usuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	E_mail VARCHAR(264) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL,
	id_Tipo_Usuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Usuario (id_Tipo_Usuario)
);

CREATE TABLE Instituicao(
	id_Instituição UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	NomeFantasia VARCHAR(100) NOT NULL,
	Endereço VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL
);

CREATE TABLE Evento(
	id_Evento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	DataEvento DATETIME NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	id_Tipo_Evento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Evento (id_Tipo_Evento),
	id_Instituição UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao (id_Instituição)
);

CREATE TABLE Presenca(
	id_Presenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Presenca BIT NOT NULL,
	id_Tipo_Usuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Usuario (id_Tipo_Usuario),
	id_Tipo_Evento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Evento (id_Tipo_Evento)
);

CREATE TABLE ComentarioEvento(
	id_ComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Descricao VARCHAR(200) NOT NULL,
	Exibe BIT NOT NULL,
	DataComentario DATETIME NOT NULL,
	id_Tipo_Usuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Usuario (id_Tipo_Usuario),
	id_Tipo_Evento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tipo_Evento (id_Tipo_Evento)
);
